### ISSUE TITLE
Falha ao rodar os testes no Bun

### ISSUE THREAD

**Issue by hiroshimorowaka** [wellwelwel/poku#161]
## Descrição da issue

Basicamente quando eu tento executar os testes utilizando o Bun como runtime ele funciona normalmente, mas ao importar algo relacionado ao Bun dentro do arquivo de teste, o poku quebra, simplesmente não executa e crasha sem mensagem de erro. 

Primeiramente eu comecei tentando importar o mock do jest de dentro do "bun:test" e crashava, ai tentei importar outras coisas de dentro do bun, de outras bibliotecas do bun e crashava. Não importa o que eu importe, se for diretamente do bun, crasha. 

### Ambiente

WSL2 Rodando Arch Linux

### Como reproduzir

Crie um arquivo de teste, no meu caso, eu criei da seguinte forma:
- | tests
  - | poku.test.ts
  
Depois dentro dele, coloque um assert pra testar e antes dele, importe qualquer lib do bun.
Exemplo:
```js
import { assert } from "poku";
import { Database } from "bun:sqlite";

assert(true, "Poku test");
```

O output desse teste é esse:

![error_output](https://github.com/wellwelwel/poku/assets/82670390/16aa41bc-7b98-49c6-82fd-9bd2bf831016)

Eu imagino que esse erro seja originado porque os testes são executados com node ao invés do próprio bun, (talvez alguma configuração que eu não soube fazer?). 
Quando é usado Typescript, os arquivos são executados com `npx tsx` e com Javascript, `node`. 
Como ele executa com node e não com o próprio Bun, imagino eu que quebre na hora de importar algo diretamente do Bun.

**Comment by hiroshimorowaka** [comment]
Eu não tinha visto que tinha que passar a flag `--platform` na hora de rodar o poku, desculpa abrir uma issue, erro de principiante. 
Agora rodou certinho.

**Comment by wellwelwel** [comment]
Fala @hiroshimorowaka, que prazer te ver por aqui 🙋🏻‍♂️

Por padrão, o **Poku** tenta identificar qual plataforma está executando ele.

Mas caso tenha mais de uma instalada (por exemplo, eu possuo tanto o Node.js, Bun e Deno), ele pode acabar entendendo o Node.js que é a base de desenvolvimento do projeto.

A opção `platform` serve tanto para evitar esse problema, como também para verificar se seu projeto é compatível com outras plataformas 🧙🏻

E não precisa se desculpar não, estou super feliz de ter um primeiro issue que não tenha sido eu mesmo que criei, haha
