### ISSUE TITLE
Show individual  and total test execution time

### ISSUE THREAD

**Issue by wellwelwel** [wellwelwel/poku#30]
## Inspiration

<img width="480" alt="erick" src="https://github.com/wellwelwel/poku/assets/46850407/0fa3a48b-5508-4d55-84fd-cce4ca5f7942">

---

**Source:** https://youtu.be/iDaBo7ge604?si=x8hWjOH8ffHHOJ_6&t=2674
**Credits** to @erickwendel 🇧🇷

**Comment by ErickWendel** [comment]
thanks a lot!! I also have it in English on that channel o/

**Comment by 1NxT** [comment]
Something like that?
![image](https://github.com/wellwelwel/poku/assets/62958414/59ead24b-0956-4df9-870d-4a12be2717a1)

**Comment by wellwelwel** [comment]
Thanks, @1NxT 🚀

I think `(0.000000ms)` should be good.

The idea would be:

- If the user use `test`, it will show the execution time for each `test` performed
- At the end of each file (using `test` method or not), it will show the total for each file
- On exit, it will show the final total of the tests

---

It's important to note that **Poku**'s `assert` simplify the test process by turning `test`, `describe` and `it` in a simple `assert(true, "Describing it")`, so it's not necessary to include an execution time for each assertion 🙋🏻‍♂️

For example:

**A)** Shows only the file and total execution time:

```js
import { assert } from 'poku';

assert.strictEqual(1, 1, 'Describing it');
```

**B)** Shows both the `test`, file and total execution times:

```js
import { test, assert } from 'poku';

// This should show the execution time
test(() => {
  // This is just an assertion
  assert.strictEqual(1, 1, 'Describing it too');
});
```

---

Feel free to discuss it 🤝

**Comment by 1NxT** [comment]
I reading the code to console log the time I used the file [parseAsssetion.ts](https://github.com/wellwelwel/poku/blob/main/src/helpers/parseAsssetion.ts) to try to measure the time of each assert.
```typescript
  var startTime = performance.now();
  const isPoku =
    typeof process.env?.FILE === 'string' && process.env?.FILE.length > 0;
  const FILE = process.env.FILE;

  try {
    ...

    if (typeof options.message === 'string') {
      var endTime = performance.now();
      const message = isPoku
        ? `${format.bold(format.success(`✔ ${options.message}`))} ${format.dim(format.success(`› ${FILE}`))} ${format.dim(`(${(endTime - startTime).toFixed(6)}ms)`)}`
        : format.bold(format.success(`✔ ${options.message}`)) + ` ${format.dim(`(${(endTime - startTime).toFixed(6)}ms)`)}`;

      console.log(message);
    }

``` 
But I don't know if it's a good approach.

**Comment by wellwelwel** [comment]
> I was reading the code trying console log the time

@1NxT, I believe that `perf_hooks` would be a good approach (I didn't get to try it):

```ts
import { performance } from 'perf_hooks';

const start = performance.now();
const end = performance.now();
const total = (end - start).toFixed(6);
```

---

We could begin with the total time per file:

**Start:**
https://github.com/wellwelwel/poku/blob/5664980c22e024b91d94ea45c3e2ab74f6d36581/src/services/run-test-file.ts#L96

**Stop:**
https://github.com/wellwelwel/poku/blob/5664980c22e024b91d94ea45c3e2ab74f6d36581/src/services/run-test-file.ts#L115

---

> **Note to self**
> 
> It would be interesting not to affect the execution time of the test itself with the Poku process, but we could think about this later.
