### ISSUE TITLE
Make it possible to use glob patterns

### ISSUE THREAD

**Issue by mrazauskas** [wellwelwel/poku#555]
Thanks for Poku! I was looking for a lightweight test runner for some time.

Just wondering, if glob pattern was overlooked or there are some limitation? I have in mind glob patterns which are expanded by a shell.

For instance, I am used to add prefix to group tests files, so that a command like `mocha tests/api-*` would run `tests/api-x.test.js`, `tests/api-y.test.js`, `tests/api-z.test.js`. This works because shells expands `*` and the actual command looks like this: `mocha tests/api-x.test.js tests/api-y.test.js tests/api-z.test.js`.

Currently `poku tests/api-*` runs only the `tests/api-z.test.js` file.

**Comment by wellwelwel** [comment]
Thanks, @mrazauskas 🙋🏻‍♂️

I can study a lib to allow glob as well.
I agree that allowing glob patterns would be a great feature.

It's currently possible to use the `--filter` and `--exclude` flags, but they're _regex-based_:

```sh
npx poku --filter='api-'
# or
npx poku --filter='api-' test
```

---

> Just wondering, if glob pattern was overlooked or there are some limitation?

The main point for direct dependencies is to keep the same compatibilities (**Node.js 8+**, **Bun**, and **Deno**) — preferably without sub-dependencies to keep it light 🙋🏻‍♂️

**Comment by mrazauskas** [comment]
Just to clarify, try running `poku tests/api-*` (or similar) in Node.js and if you look at `process.argv.slice(2)` you will see something like:

```js
["tests/api-x.test.js", "tests/api-y.test.js", "tests/api-z.test.js"]
```

There is no need for dependencies. Many shells are expanding globs. The only limitation is that Poku currently only considers the last path.

**Comment by wellwelwel** [comment]
**Poku** uses a simple approach with `readdir`:

https://github.com/wellwelwel/poku/blob/71df0acbd096eac8286f39a8afd8cc87a49423d6/src/modules/helpers/list-files.ts#L42

---

> The only limitation is that Poku currently only considers the last path.

To use the import in any order, you can use the `--include`, for example:

```json
{
  "test": "poku --include=test"
}
```

```sh
npm run test -- --filter=api-
```

---

At the moment I'm creating a basic feature to allow configuration files (`json` and `jsonc`), then I'll look into it more carefully.

**Comment by wellwelwel** [comment]
### Note to self

#### Unix

```sh
find test -type f -path "test/**/*.test.*"
```

#### Windows

```shell
Get-ChildItem -Path test -Recurse -File | Where-Object { $_.FullName -match '\.test\.' } | Select-Object -ExpandProperty FullName
```

**Comment by mrazauskas** [comment]
#562 does all what I wanted. Just tried out the latest release, this is exactly what I wanted. Thanks!

Not sure I understand the rest of your plans. Looks complicated and the implementation likely will be platform specific. For instance, users might want to reuse some CLI command with `matrix` in CI. In this context, platform specific behaviour adds unnecessary complexity. Just saying, you know what you are doing and this is your project (;

**Comment by wellwelwel** [comment]
Thanks again, @mrazauskas 🤝

I like to save a lot of ideas and I use “note to self” for this, but my priorities at the moment are different.

Since the project is getting some interaction, I feel it's worth mentioning my plans 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
After thinking about it for a while, especially after the discussion generated in #608, I believe that glob isn't a suitable feature for **Poku** at the moment.

Together with the #608 fix, I'll include alternatives to the docs like the ones you suggested (and provided).

**Comment by mrazauskas** [comment]
Sure. My only concern was globs which are expanded by the shell. This is already working as expected.
