### ISSUE TITLE
Parametrized tests

### ISSUE THREAD

**Issue by mrazauskas** [wellwelwel/poku#566]
@wellwelwel What are your thoughts on parametrized tests?

Might be there is an example in documentation. Sorry, if I missed it.

I am trying to migrate from Mocha. Currently I have asynchronous `before`, asynchronous `after` and `.forEach()` is used to loop through test cases.

Looks like I have to replace `.forEach()` with `Promise.all` to make this work. It just felt like this could be a good addition for documentation. In the other hand, perhaps you have some plans for `test.each` or similar?

**Comment by wellwelwel** [comment]
Hey, @mrazauskas 🙋🏻‍♂️

In fact, it's a missing example.

---

An approach like the following can be an interesting aid to this:

```ts
import { test, beforeEach, afterEach, strict } from 'poku';

const testCases = [
  [{ name: 'Alice', role: 'admin' }, true],
  [{ name: 'Bob', role: 'user' }, false],
  [{ name: 'Charlie', role: 'guest' }, false],
];

const isAdmin = (user) => user.role === 'admin';

describe('Testing privileges', async () => {
  beforeEach(async () => {
    // setup
  });

  afterEach(async () => {
    // teardown
  });

  await test.each(testCases)((user, expected) => {
    const actual = isAdmin(user);

    strict.strictEqual(
      actual,
      expected,
      'should return %s for user with role %s'
    );
  });
});
```

---

What do you think of this approach?

> It seems to fit in well with the concept of preserving a **JavaScript** _syntax-faithful_ approach without sacrificing useful features for testing.

**Comment by mrazauskas** [comment]
What you think about simply using `for..of`? Here is more or less what I did:

```js
import { assert, test } from "poku";

const testCases = [
  {
    expected: true,
    input: { name: "Alice", role: "admin" },
    testCase: "is admin",
  },
  {
    expected: false,
    input: { name: "Bob", role: "user" },
    testCase: "is not admin",
  },
];

const isAdmin = (user) => Promise.resolve(user.role === "admin");

for (const { expected, input, testCase } of testCases) {
  await test(testCase, async () => {
    const actual = await isAdmin(input);

    assert.strictEqual(actual, expected);
  });
}
```

---

You know better how Poku would handle this code. So are there any down sides?

**Comment by wellwelwel** [comment]
This is a great example. Would you like to contribute to it?

> You know better how Poku would handle this code. So are there any downsides?

Not exactly a downside, although the philosophy is to bring **JavaScript** syntax into tests, creating _hooks_ for specific situations could remove extra complexities or be a viable alternative for those already used to current approaches (this comes more as “ideas” than “downsides”).

**Comment by wellwelwel** [comment]
`[OFF]` Your [docusaurus-remark-plugin-tab-blocks](https://github.com/mrazauskas/docusaurus-remark-plugin-tab-blocks) project is really interesting. I'm planning to bring it into **Poku**'s documentation.

**Comment by wellwelwel** [comment]
> You know better how Poku would handle this code. So are there any downsides?

Also, in cases with a single `assert`, I would recommend using the message on `assert` in preference to the `test` / `it`:

#### assert

> <img width="485" alt="assert" src="https://github.com/user-attachments/assets/b48cc615-82f0-4cea-aa65-22d2933fcdc0">

#### test/it

> <img width="485" alt="test-it" src="https://github.com/user-attachments/assets/6c2556cc-a90b-4589-b6a0-8d62df004931">

#### By combining

> <img width="485" alt="Screenshot 2024-07-21 at 07 35 42" src="https://github.com/user-attachments/assets/729adf07-24f2-4c90-b8e6-8d3f59477ecc">

**Comment by mrazauskas** [comment]
> `[OFF]` Your [docusaurus-remark-plugin-tab-blocks](https://github.com/mrazauskas/docusaurus-remark-plugin-tab-blocks) project is really interesting. I'm planning to bring it into **Poku**'s documentation. Thanks for this ✨

Glad to hear. I just migrated `docusaurus-remark-plugin-tab-blocks` tests to Poku (;
