### ISSUE TITLE
"Coverage 100%" badge is misleading

### ISSUE THREAD

**Issue by mrazauskas** [wellwelwel/poku#578]
While trying to migrate a larger code base to Poku, I bump into an issue with async `afterEach()` and async `test()`. Moving code from `afterEach()` to the end of `test()` makes all work as expected. (I will create reproduction later.)

Out of curiosity I looked at: [`src/modules/helpers/test.ts`](https://github.com/wellwelwel/poku/blob/main/src/modules/helpers/test.ts). If I get it right, the `test()` helper logic lives here. Unfortunately the promise handling logic is wrapped with `c8 ignore` comments. Hm.. Might be I miss something, but at first glance it does not like these lines are not reachable.

"Coverage 100%" badge looks beautiful, but now for me it feels misleading. The high coverage rate was one of the aspects why I decided to migrate to Poku. Please consider updating the badge with actual coverage information.

**Comment by wellwelwel** [comment]
Hey, @mrazauskas.

The only mention for this is in 9Contributing.md](https://github.com/wellwelwel/poku/blob/main/CONTRIBUTING.md):

https://github.com/wellwelwel/poku/blob/2b1eff045f1d7c2804b26fcb18120d3eb7042297/CONTRIBUTING.md#L116-L118

---

I use two specific comments that are related to some problem between c8 and tsx:

```js
/* c8 ignore next */ // ?
```

- For some reason, the first line of some files and the last export always appear as zero coverage, including when the line is a comment.

```js
/* c8 ignore next */ // Types
```

- When using overloads or importing types (`ts`), **tsx** build removes it before running, causing coverage mistakes.

---

Except by these two, all other comments should fit on `process` or `Windows`, previous versions from **Node.js** or vary for **Bun** and **Deno**.

---

Being honest, I loved the nudge and will revisit all the c8 comments, thank you for that.

I'm considering migrating from c8 to **monocart-coverage-reports**.

I apologize for any misunderstanding and would like to hear your opinion on these exceptions I mentioned. I really want to cover 100% of the project.

**Comment by mrazauskas** [comment]
All is fine. This is only a badge (;

By the way, I was thinking to recommend looking at `monocart-coverage-reports`. It is really good in filtering out type only or empty lines. And the native `v8` / `codecov` coverage is their strong side.

**Comment by wellwelwel** [comment]
I opted to pin your issue, this is the most complex project I've ever developed and I love it _(from the code, every documentation detail and even the mascot's artwork)_.

There are exclusive tests for **Deno** and **Bun**, but they aren't compatible with the **c8**.

I'll look into it soon and thank you again for the alert.

**Comment by mrazauskas** [comment]
By the way, those `c8 ignore` comments are shipped to `npm` and increase the install size without being anyhow useful. Just another argument (;

**Comment by wellwelwel** [comment]
> By the way, those `c8 ignore` comments are shipped to `npm` and increase the install size without being anyhow useful. Just another argument (;

Yes, it bothers me a lot.

I tried a test locally with `monocart-coverage-reports` and only 8 comments remained 🎉

Most due to process, for example:

```ts
/* c8 ignore next 3 */ // Process
export const onSigint = () => {
  process.stdout.write('\u001B[?25h');
};

/* c8 ignore next */ // Process
process.once('SIGINT', onSigint);
```

**Comment by wellwelwel** [comment]
## For community

If you don't agree with any of these not covered topics, please feel free to comment:

- `process-based` (e.g., `process.exit`, `process.once`, etc.)
- Different behaviors due to platform versions (e.g., **Node.js** `v8`, `v12`, etc.)
- Different behaviors due to **Deno** and **Bun** platforms
- Different behaviors due to _OS_ _(**Windows**)_
  - I'm planning to remove this one, since we can use **Windows** matrix for _CI_

> In disagreements, this issue can be reopened at any time 🤝

---

## Related

- https://github.com/wellwelwel/poku/pull/585

**Comment by wellwelwel** [comment]
> The high coverage rate was one of the aspects why I decided to migrate to Poku.

Less formal, I don't want anyone to feel that way when using Poku, which is why I'm taking it so seriously.

**Comment by mrazauskas** [comment]
I appreciate the effort. Thank you.

**Comment by wellwelwel** [comment]
Converting this issue to a discussion in favor of #612.
