### ISSUE TITLE
Typings of `test()` and `it()`

### ISSUE THREAD

**Issue by mrazauskas** [wellwelwel/poku#579]
The most simple overload of `test()` and `it()` has this shape:

https://github.com/wellwelwel/poku/blob/2b1eff045f1d7c2804b26fcb18120d3eb7042297/src/modules/helpers/test.ts#L14

Strangely if a `message: string` is added as the first argument, the function becomes async and returns `Promise<void>`:

https://github.com/wellwelwel/poku/blob/2b1eff045f1d7c2804b26fcb18120d3eb7042297/src/modules/helpers/test.ts#L12

Just wondering if this is correct?

**Comment by wellwelwel** [comment]
Using `test` or `it` without messages helps to better organize the scope, even if it doesn't affect the output or test results:

```ts
test(() => {
  // ...
});
```

By using a message first, it keeps the above idea, but changes the behavior of test output.

```ts
test('...', () => {
  // ...
});
```

---

But on closer observation, each of these two overloads should be output as `Promise<void>` / `void`, so it's seems missing two overloads.

**Comment by mrazauskas** [comment]
It should always return `Promise<void>`? Or?

**Comment by wellwelwel** [comment]
It should be like this:

- No message + cb: `void`
- Message + cb: `void`
- No message + async cb: `Promise<void>`
- Message + async cb: `Promise<void>`
