### ISSUE TITLE
Add the `--listFiles` command line option

### ISSUE THREAD

**Issue by mrazauskas** [wellwelwel/poku#590]
Many test runners have the `--listFiles` command line option. For example:

```shell
npx poku --filter="unit" --listFiles
```

Should emit list of files selected for the run (without executing them).

In a larger code base, this helps to debug commands.

**Comment by wellwelwel** [comment]
@mrazauskas, I'll focus on migrating to `monocart-coverage-reports` before moving back to the `feature request` labels.

Thanks for all the ideas and reports you're bringing to **Poku** 🤝
