### ISSUE TITLE
Add the `--help` command line option

### ISSUE THREAD

**Issue by mrazauskas** [wellwelwel/poku#592]
Help is helpful (; Why not?

**Comment by wellwelwel** [comment]
It's a good ideia, thanks!

**Comment by mrazauskas** [comment]
For inspiration, take a look how elegant `--help` is implemented in Zora:

https://github.com/lorenzofox3/zora/blob/a2503f96fe1172da0f72e39353823869b9a39a94/pta/src/bin.js#L54-L56

**Comment by wellwelwel** [comment]
> For inspiration, take a look how elegant `--help` is implemented in Zora:

Thanks, that made it much easier.
