### ISSUE TITLE
Use `os.availableParallelism()` to calculate default `concurrency`

### ISSUE THREAD

**Issue by mrazauskas** [wellwelwel/poku#603]
Please consider using `os.availableParallelism()` to calculate default `concurrency`.

The API is not available on older versions of Node.js, but I think that is fine. In those cases it can default to `0` or so.

The unlimited concurrency is too eager. Especially in CI. I understand that `--concurrency` can be set manually, but the value must be guessed. Instead `os.availableParallelism()` could provide it taking into account available resources.

**Comment by wellwelwel** [comment]
I'll check compatibility with other platforms.

I think it could be released as a `fix:`, since in large projects unlimited execution is a concern. Then, if `os.availableParallelism()` is not available, we could keep as it is.

**Comment by wellwelwel** [comment]
<blockquote>

### Note to self

- Check for `const availableParallelism = os.cpus().length` when `os.availableParallelism()` is not available.

</blockquote>

**Comment by mrazauskas** [comment]
`os.cpus().length` should be good fallback.

Just to draw your attention, here is how Jest handles number of workers: https://github.com/jestjs/jest/blob/b8c5200451b89bab85e42f5e9a29bcd13d00c894/packages/jest-config/src/getMaxWorkers.ts#L38

It sounds feasible to use only 50% of available core in the watch mode.

**Comment by wellwelwel** [comment]
> Just to draw your attention, here is how Jest handles number of workers: https://github.com/jestjs/jest/blob/b8c5200451b89bab85e42f5e9a29bcd13d00c894/packages/jest-config/src/getMaxWorkers.ts#L38
> 
> It sounds feasible to use only 50% of available core in the watch mode.

Thanks for the idea.

I've done something quite similar, but treating it as a polyfill.
