### ISSUE TITLE
Add the `disableIsolation` option

### ISSUE THREAD

**Issue by mrazauskas** [wellwelwel/poku#615]
Perhaps it would be possible to add the `disableIsolation` option?

From time to time Jest is receiving similar requests. They are declined and I understand why. Feel free to say no.

In the other hand, there are project that do not need isolation. And disabling it would improve performance.

I like the idea to isolate test files by default, but allowing to disable this feature makes it possible to optimise performance for larger projects that do not benefit from the isolation.

**Comment by mrazauskas** [comment]
By the way, Vitest has an option to disable `isolation`: https://vitest.dev/guide/improving-performance.html

**Comment by wellwelwel** [comment]
> They are declined and I understand why. Feel free to say no.

I'm fine with that idea. In order not to lose the idea of being able to run ESM and CJS in the same test flow, I could make this option possible from version **Node.js 12**.

As this would require a large refactoring, it wouldn't be a priority, but it's something that would be nice to have in the plans.

**Comment by wellwelwel** [comment]
> we could make this option possible from version Node.js 12 (Bun and Deno would work naturally)

It's not something I'd like to cause a breaking change over:

https://github.com/wellwelwel/poku/blob/4c3f289c1977b05e6d8e784a804b9f5319c3ec2d/website/docs/philosophy.mdx#L291-L296

**Comment by mrazauskas** [comment]
Or perhaps some option to provide a custom runner module?

**Comment by wellwelwel** [comment]
> Or perhaps some option to provide a custom runner module?

This polyfill does a dynamic import, but using `require` through an ES module:

> It is used to allow CommonJS projects to be tested with **Deno**.

https://github.com/wellwelwel/poku/blob/4c3f289c1977b05e6d8e784a804b9f5319c3ec2d/src/polyfills/deno.mts#L10-L17

The difference would be to identify whether the environment has `require` or `import` in order to perform the import dynamically.

> [!NOTE]
> 
> The refactoring I mentioned refers to the fact that the entire **Poku** is based on sub-processes.

**Comment by mrazauskas** [comment]
Would it help if the `runner` could be only ESM module? I think that is fine.

By the way, why CommonJS projects should be tested with Deno?

**Comment by wellwelwel** [comment]
> Would it help if the `runner` could be only an ESM module? I think that is fine.
> 
> By the way, why CommonJS projects should be tested with Deno?

The answer is the same for both questions 🐷

---

When I created the prototype of what would become **Poku**, the idea was to have a flexible runner to test **MySQL2** on other platforms.

Just like **MySQL2**, many packages are provided as CommonJS and allow interoperability between ES Modules:

```js
const mysql2 = require('mysql2');
```

```js
import mysql2 from 'mysql2';
```

---

**Deno** doesn't allow you to run **CJS** files directly if they don't come directly from imports such as `npm:mysql2`. So, how do I test MySQL2 through **Deno**?

That's what this polyfill is designed for.

> You can think on it like "Is my package compatible with Deno when imported via **npm**?" 🦖

---

**Poku** also considers creators and maintainers of libraries and packages directly. It's not just about “running on any platform”.

### A curiosity

<blockquote>

After many failures to create a cross-platform runner, a thought came to me: “They're all designed to run JavaScript. What if...?”

And that's where the philosophy of having a test runner that emphasizes JavaScript's native syntax came from 🙋🏻‍♂️

</blockquote>

---

**cc:** @sidorares

**Comment by mrazauskas** [comment]
Interesting. To be honest, I don’t know much about Bun or Deno. My idea is to make TSTyche work with Bun and Deno at some point. So I was planing to dive deeper into that this autumn. The first problem was testing. Looks like this got solved (;

**Comment by mrazauskas** [comment]
Wait.. If I run

```shell
node someTestFile.js
```

there will be no processes spawned by Poku and I will have no isolation? Or?

**Comment by wellwelwel** [comment]
> Wait.. If I run
> 
> ```shell
> node someTestFile.js
> ```
> 
> there will be no processes spawned by Poku and I will have no isolation? Or?

Yes, it's right 🙋🏻‍♂️

**Comment by mrazauskas** [comment]
Nice! I will play with that.

**Comment by mrazauskas** [comment]
The result surprised me. I was playing with the heavy tests from TSTyche, the ones that are picked by the `test:e2e:serial` script:

- `poku`, 161.85 s
- `node`, 160.311 s
- `mocha`, 3 min

I guess this means that `disableIsolation` is not helpful. But it was worth a try, of course.

Also the `runner` option is not needed, because it is already possible to write a custom runner ;D

Thanks for your time and all the tips.
