### ISSUE TITLE
Ensure that only JavaScript or TypeScript files are executed

### ISSUE THREAD

**Issue by wellwelwel** [wellwelwel/poku#617]
I realized that when using filters, it's possible to accidentally bring in unrecognized files (e.g., `Community.md` for `filter=unit`).

**Comment by mrazauskas** [comment]
I have bump into this too. But isn't it that `filter` is pattern that selects test files? I mean, these can be any files user wants to execute.

In contrast `exclude` should always get a list of files that already passed through `filter`.

At first I thought `filter` is just opposite from `exclude`, but it's not. Right? So I think it should allow the user to decide and to make mistakes too.

In other words, I see it more like `testFilePattern`. All what is matching the pattern is a test file. The rest are not. In a way `--filter=unit` does not make sense. That should be `--filter='.test.|.spec.' --include=unit --exclude=internal`. Or so.

**Comment by wellwelwel** [comment]
> So I think it should allow the user to decide and to make mistakes too.

Do you mean that this might not necessarily be a bug?

**Comment by wellwelwel** [comment]
> At first I thought `filter` is just opposite from `exclude`, but it's not. Right?

Both handle the same list returned by `readdir`, where `exlude` has priority over `filter`.

**Comment by wellwelwel** [comment]
I agree with the idea of the user being able to filter and exclude what they want. 

I believe that in the future, other users may come across this issue too.
Instead of filtering it as `filter=unit`, we can just use `filter=unit/`, for example.

@mrazauskas, thanks for pointing that out.

**Comment by mrazauskas** [comment]
Just trying to describe how I would design the logic. First, `filter` test files from provided list. Next leave only included files if `include` was specified. Finally `exclude` what has to be excluded.

Sounds similar to what TypeScript does. But that is just a single approach, of course.

**Comment by wellwelwel** [comment]
As I hadn't imagined the use of Glob patterns being extended from shell, I wondered about possible conflicts. Since the shell forwards the list of files directly, I can't know if the command had a shell before it reached `argv`.

For this reason, I believe it's interesting to point out that it's possible to bypass the `filter`:

```sh
npx poku --filter='' ./packages/**/test/unit/*.js
```
