### ISSUE TITLE
Validate CLI flags

### ISSUE THREAD

**Issue by mrazauskas** [wellwelwel/poku#647]
Thanks for CLI improvements!

Here is another idea. I have noticed that it is too easy to make a mistake like this: `poku --failFast`. The `failFast` is primarily [documented](https://poku.io/docs/documentation/poku/options/fail-fast) using camel case (look at TOC, or heading of the page). Or someone (like me) might be used to run tests with `--failFast`.

It would be useful to see some error like: Unknown flag `--failFast`.

Edit: And another mistake I just made: `poku --paralel`.

---

Support for camel case flags is another feature, but I will mention it here too. Interestingly `tsc` supports only camel case flags. That simplifies documentation of compiler config options and CLI flags.

**Comment by wellwelwel** [comment]
Hey, @mrazauskas 🙋🏻‍♂️

I'd have no problem patterning the `camelCase`, but it would be more feasible in a future major version (`v3`).

As for validation, it's a good idea.

**Comment by mrazauskas** [comment]
Sure. This issue is about validation only.

The rest is totally up to you. Since that is opinionated and also depends on how you see Poku's future.

**Comment by mrazauskas** [comment]
I understand this is not a priority right now. Just to draw you attention: not only flag names, but also their values need validation; the same is applicable for config file options.

For example, imagine some option being removed / renamed / changed its behaviour.

Perhaps it is worth to keep this issue open?

**Comment by wellwelwel** [comment]
In a way, this functionality would frequently imply breaking changes. So, to have more flexibility, I released it as "Early Development" and documented some plans for the `enforce` option:

https://github.com/wellwelwel/poku/blob/3cb5a00b15d1fec8aa969e8e7b1ad821d2326305/website/docs/documentation/poku/options/enforce.mdx#L27-L29

- More ideas are welcome 🙋🏻‍♂️

Also:

https://github.com/wellwelwel/poku/blob/3cb5a00b15d1fec8aa969e8e7b1ad821d2326305/website/docs/documentation/poku/options/enforce.mdx#L39-L41

---

> Perhaps it is worth to keep this issue open?

For now, I'm using the documentation itself as if it were an issue (with the idea of emphasizing that this feature is still under development). Honest question, do you think this is a bad idea?

**Comment by wellwelwel** [comment]
> For example, imagine some option being removed / renamed / changed its behaviour.

About this, I tend to take versioning pretty carefully, for example, to make it easier to migrate from camel case, I've allowed both kebab and camel cases until a new major version is actually released.

In addition, the intention is for the `enforce` to notify depreciated options. For example, even allowing `fast-fail`, when using `enforce` it will throw an error because it expects `failFast`.
