### ISSUE TITLE
`--version` is incorrect in canary releases

### ISSUE THREAD

**Issue by mrazauskas** [wellwelwel/poku#748]
Installing `poku@canary` and running `poku --canary` prints: `2.6.0`. Altho the version in `node_modules/poku/package.json` is `2.6.1-canary.c53f3e3`.

**Comment by wellwelwel** [comment]
Thanks for the notice. Already fixing in #750 🙋🏻‍♂️

I like to release a new version every two updates or more _(it's not a rule)_. That's why I thought it would be interesting to have a canary version.

**Comment by wellwelwel** [comment]
**npm** is returning `(502) Bad Gateway`, I'll keep it open for now.
