### ISSUE TITLE
Typings of `test()` and `test.skip()` differ 

### ISSUE THREAD

**Issue by mrazauskas** [wellwelwel/poku#749]
Technically all is correct, of course. But... the problem is that some tooling recommends removing `await`, if `.skip` is used with async test:

<img width="568" alt="Screenshot 2024-09-08 at 08 40 08" src="https://github.com/user-attachments/assets/ef9bcd85-6265-4f10-8456-430e19e5eab8">

Here that is just a misleading recommendation. I did not try, but in some situation `await` could get removed automatically (after applying lint rules on save). Does not look like this is needed, if the test is disable only temporary.

**Comment by wellwelwel** [comment]
Although **TypeScript** checks the compilation, I really need to create overload tests to avoid these situations.

Linking this to remember: https://github.com/tstyche/tstyche/discussions/265#discussioncomment-10158707
