### ISSUE TITLE
RangeError: Invalid count value in Write.hr function

### ISSUE THREAD

**Issue by xenokratos** [wellwelwel/poku#829]
Hi!

When running my tests on CircleCI, I got into `RangeError` in this code ⬇️ 

```ts
const line = '─'.repeat(node_process_1.stdout.columns - 10 || 40);
```

![Screenshot 2024-10-27 at 02 42 39](https://github.com/user-attachments/assets/82f9baf6-cf47-4b55-946c-0531a2fd2645)

`process.stdout.columns` Seems to equal 0, when running from a CI env.

Similar issue can be found here https://github.com/google/zx/issues/607

**Comment by wellwelwel** [comment]
Thanks for the report, @xenokratos 🙋🏻‍♂️
