### ISSUE TITLE
Use a queue for parallel tests instead of a group

### ISSUE THREAD

**Issue by sirenkovladd** [wellwelwel/poku#849]
Maintains steady concurrency level throughout execution
similar to [fastq](https://www.npmjs.com/package/fastq)

https://github.com/wellwelwel/poku/blob/main/src/services/run-tests.ts#L92-L145

**Comment by wellwelwel** [comment]
@sirenkovladd, I'm working on it in #886. For now, Poku's own test suite clarifies the difference:

**Linux**: ~19% faster
**macOS**: ~21% faster
**Windows**: ~23% faster

- These rates can be even higher in extremely long and time-consuming tests, and can exceed 50%, helping to understand what happened in https://github.com/tstyche/tstyche/pull/295.

Thanks for your help, this enhancement will have a huge impact on **Poku**.

> [!NOTE]
> I chose not to bring this improvement to Poku `v2`, as I don't intend to offer updates for this version except for security patches (until version 3 is officially released).
